name: Hourly Data Feeder

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run_feature_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # FIX: Pin version to 4.2.4 to match Server
      - name: Install Dependencies
        run: pip install hopsworks==4.2.4 pyarrow pandas requests python-dotenv numpy

      - name: Run Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python features/2_feature_pipeline.py