name: Hourly Data Feeder

on:
  schedule:
    - cron: '0 * * * *'  # Runs at minute 0 of every hour
  workflow_dispatch:      # Allows you to click a button to run it manually

jobs:
  run_feature_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # FIX: Added "hopsworks[python]" to install pyarrow automatically
      - name: Install Dependencies
        run: pip install "hopsworks[python]" pandas requests python-dotenv numpy

      - name: Run Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python features/2_feature_pipeline.py